ci: gitlab: add check for coverage file integrity
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -127,6 +127,24 @@ unittests:
   <<: *linux-dub_definition
   variables:
     BUILD_DUB_FLAGS: $CI_JOB_STAGE --build=unittest
+  before_script:
+    - |
+      echo "--> Check for integrity of generated coverage files..."
+      (cd tests/res;
+        for d_file in `find . -maxdepth 1 -type f -exec echo {} \; | cut -c3- | grep '.d$'`; do
+            dmd -cov -unittest -main "$d_file"
+            ./"${d_file%.*}" > /dev/null
+        done
+      )
+      for file in `git diff --name-only | grep ".lst$"`; do
+        echo "ERROR: File '$file' need to be regenerated."
+        DCOV_FILE_FOUND=1
+      done
+
+      if [ "$DCOV_FILE_FOUND" == "1" ]; then
+        exit 1;
+      fi
+
 
 code_coverage:
   <<: *linux-dub_definition
